repos:
  - repo: local
    hooks:
      - id: fish-format
        name: Format Fish files
        entry: ./scripts/format.fish
        language: system
        files: \.fish$
        pass_filenames: false
        verbose: true
        always_run: false
        stages: [manual]