repos:
  - repo: local
    hooks:
      - id: fish-format
        name: Format Fish files
        entry: ./scripts/format.fish
        language: system
        files: \.fish$
        pass_filenames: false
      - id: fish-check-format
        name: Check Fish formatting
        entry: ./scripts/check-format.fish
        language: system
        files: \.fish$
        pass_filenames: false