repos:
  - repo: local
    hooks:
      - id: fish-format
        name: Format Fish files
        entry: ./scripts/format.fish
        language: system
        files: \.fish$
        pass_filenames: false
        verbose: true
        always_run: false
        stages: [manual]
      - id: markdown-format
        name: Format Markdown files
        entry: ./scripts/format-md.fish
        language: system
        files: \.md$
        pass_filenames: false
        verbose: true
        always_run: false
        stages: [manual]